before_script:
  # login to docker registry
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

services:
  - docker:dind

variables:
  IMAGE_NAME: registry.gitlab.com/swarmfund/api
  IMAGE_BUILD_NAME: $IMAGE_NAME:$CI_COMMIT_SHA
  IMAGE_RELEASE_NAME: $IMAGE_NAME:latest

stages:
  - build
    
build-production:
  image: docker:latest
  stage: build
  script:
    - docker build --pull -t $IMAGE_BUILD_NAME .
    - docker push $IMAGE_BUILD_NAME
    - docker tag $IMAGE_BUILD_NAME $IMAGE_RELEASE_NAME
    - docker push $IMAGE_RELEASE_NAME
