before_script:
  # login to docker registry
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN registry.gitlab.com

# docker-in-docker allows to build and publish docker images
services:
  - docker:dind

variables:
  # dockerfile for building test image
  TEST_DOCKERFILE: test.dockerfile
  # dockerfile for building artifact image
  BUILD_DOCKERFILE: build.dockerfile
  IMAGE_NAME: registry.gitlab.com/swarmfund/api
  IMAGE_BUILD_NAME: $IMAGE_NAME:$CI_COMMIT_SHA
  IMAGE_TEST_NAME: $IMAGE_NAME:$CI_COMMIT_SHA-test
  IMAGE_RELEASE_NAME: $IMAGE_NAME:latest

stages:
  - build
  - test
  # TODO pages

# build and publish docker image to the registry
build:
  image: docker:latest
  stage: build
  script:
    - docker build --pull -t $IMAGE_BUILD_NAME -f $BUILD_DOCKERFILE .
    - docker push $IMAGE_BUILD_NAME
    - docker tag $IMAGE_BUILD_NAME $IMAGE_RELEASE_NAME
    - docker push $IMAGE_RELEASE_NAME

# build testing image and run tests
test:
  image: docker:latest
  stage: test
  script:
    - docker build --pull -t $IMAGE_TEST_NAME -f $TEST_DOCKERFILE .
    - docker run $IMAGE_TEST_NAME ./...