api:
  database_url: postgres://postgres@localhost/api?sslmode=disable
  horizon_url: http://localhost:8000
  account_manager: SBMFQCGDVJBC2NYBRPURK3ISC4XJGGOLHMGHF7MIHVXE2DIQSMY6NYRH
  # disable only signature validity check
  skip_signature_check: true

horizon:
  url: http://localhost:8000
  signer: SB73STJOWULYZNPGDLNRBAYGMROB47ATNKM723XORFBLI356U3SKMARZ

notificator:
  client_router: http://localhost:8888/hredir
  endpoint: http://localhost:9009
  #secret: foo
  #public: bar

http:
  host: localhost
  port: 8001

log:
  level: error
  slow_query_bound: 300ms
  slow_request_bound: 1s


sentry:
  dsn: http://9be51faad32741f3a18020fa29982edf:aa57a4cad13740ca8957c79100e4c9a7@128.199.229.140:9090/9
  level: warn

storage:
  host: "localhost:9000"
  # minio credentials
  access_key: "2SRMRAST49JEIMUUKWKH"
  secret_key: "vm7+HyjPijP6xgzzjsxJrUs7dJgim0mj+K/lD2im"
  force_ssl: false
  media_types:
    - 'application/pdf'
    - 'image/jpeg'
    - 'image/tiff'
    - 'image/png'
    - 'image/gif'

wallet_cleaner:
  enabled: true
  expiration: 128h