api:
  database_url: postgres://postgres@localhost/api_swarm?sslmode=disable
  horizon_url: http://localhost:8000
  account_manager: SBMFQCGDVJBC2NYBRPURK3ISC4XJGGOLHMGHF7MIHVXE2DIQSMY6NYRH
  skip_signature_check: true

storage:
  # gracefully disable storage services
  disabled: true
  host: "localhost:9000"
  # minio credentials
  access_key: "2SRMRAST49JEIMUUKWKH"
  secret_key: "vm7+HyjPijP6xgzzjsxJrUs7dJgim0mj+K/lD2im"
  # amqp bucket notification arn
  object_create_arn: "arn:minio:sqs:us-east-1:1:amqp"
  # amqp broker connection string
  listener_broker_url: "amqp://guest:guest@localhost:5672"
  # amqp exchange name
  listener_exchange: "document"
  # optional amqp exchange type, default "direct"
  listener_exchange_type: "direct"
  # amqp topic binding key
  listener_binding_key: "events"
  force_ssl: false
  form_data_expire: 50000

notificator:
  client_router: http://localhost:8888/hredir
  endpoint: http://95.85.47.33:7000
  #secret: foo
  #public: bar

http:
  host: localhost
  port: 8001

log:
  level: info