api:
  project: Human Readable Name
  database_url: postgres://postgres@localhost/api?sslmode=disable
  horizon_url: http://localhost:8000
  account_manager: SBMFQCGDVJBC2NYBRPURK3ISC4XJGGOLHMGHF7MIHVXE2DIQSMY6NYRH
  # disable only signature validity check
  skip_signature_check: true
  horizon_signer: SB73STJOWULYZNPGDLNRBAYGMROB47ATNKM723XORFBLI356U3SKMARZ

horizon:
  url: http://localhost:8000
  signer: SB73STJOWULYZNPGDLNRBAYGMROB47ATNKM723XORFBLI356U3SKMARZ

notificator:
  client_router: http://localhost:8888/hredir
  endpoint: http://localhost:9009
  disabled: true
  #secret: foo
  #public: bar

salesforce:
  api_url: "https://xxxxxx.salesforce.com/"
  client_secret: "1234567"
  client_id: "XXXXXXXXXXXXXXXXXXXXXXXX"
  username: "test@test.test"
  password: "qwerty"


http:
  host: localhost
  port: 8001

log:
  level: error
  slow_query_bound: 300ms
  slow_request_bound: 1s


sentry:
  dsn: http://9be51faad32741f3a18020fa29982edf:aa57a4cad13740ca8957c79100e4c9a7@128.199.229.140:9090/9
  level: warn

storage:
  host: "localhost:9000"
  # minio credentials
  access_key: "2SRMRAST49JEIMUUKWKH"
  secret_key: "vm7+HyjPijP6xgzzjsxJrUs7dJgim0mj+K/lD2im"
  force_ssl: false
  media_types:
    general:
      - 'image/jpeg'
      - 'image/tiff'
      - 'image/png'
      - 'image/gif'
    alpha:
      - 'application/pdf'
    bravo:
      - 'application/pdf'


wallet_cleaner:
  enabled: true
  expiration: 128h
