[[constraint]]
  branch = "default"
  name = "bitbucket.org/ww/goautoneg"

[[constraint]]
  name = "github.com/asaskevich/govalidator"
  version = "7.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/go-errors/errors"

[[constraint]]
  branch = "master"
  name = "github.com/goji/context"

[[constraint]]
  name = "github.com/guregu/null"
  version = "3.2.0"

[[constraint]]
  branch = "master"
  name = "github.com/jmoiron/sqlx"

[[constraint]]
  name = "github.com/lann/squirrel"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/lib/pq"

[[constraint]]
  name = "github.com/minio/minio-go"
  version = "3.0.3"

[[constraint]]
  name = "github.com/mssola/user_agent"
  version = "0.4.1"

[[constraint]]
  branch = "master"
  name = "github.com/multiplay/go-slack"

[[constraint]]
  name = "github.com/patrickmn/go-cache"
  version = "2.1.0"

[[constraint]]
  name = "github.com/pkg/errors"
  version = "0.8.0"

[[constraint]]
  name = "github.com/pquerna/otp"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/rcrowley/go-metrics"

[[constraint]]
  branch = "master"
  name = "github.com/rubenv/sql-migrate"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.3"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.1"

[[constraint]]
  name = "github.com/spf13/viper"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "github.com/streadway/amqp"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "1.1.4"

[[constraint]]
  name = "github.com/zenazn/goji"
  version = "1.0.0"

[[constraint]]
  branch = "master"
  name = "gitlab.com/distributed_lab/notificator"

[[constraint]]
  name = "gitlab.com/distributed_lab/skrill-go"
  version = "0.0.1"

[[constraint]]
  name = "gitlab.com/distributed_lab/sse-go"
  version = "1.0.0"

[[override]]
  name = "gitlab.com/tokend/go"
  branch = "feature/signcontrol-v2"

[[constraint]]
  name = "gitlab.com/tokend/horizon-connector"
  branch = "master"

[[constraint]]
  branch = "master"
  name = "golang.org/x/net"

[[constraint]]
  name = "gopkg.in/tylerb/graceful.v1"
  version = "1.2.15"

[[constraint]]
  branch = "master"
  name = "gitlab.com/distributed_lab/figure"

[[constraint]]
  name = "gitlab.com/distributed_lab/ape"
  version = "v0.2"