// Code generated by mockery v1.0.0
package mocks

import mock "github.com/stretchr/testify/mock"

// CoreInfoI is an autogenerated mock type for the CoreInfoI type
type CoreInfoI struct {
	mock.Mock
}

// GetMasterAccountID provides a mock function with given fields:
func (_m *CoreInfoI) GetMasterAccountID() string {
	ret := _m.Called()

	var r0 string
	if rf, ok := ret.Get(0).(func() string); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}
