// Code generated by mockery v1.0.0
package config

import mock "github.com/stretchr/testify/mock"

// mockRawGetter is an autogenerated mock type for the rawGetter type
type mockRawGetter struct {
	mock.Mock
}

// GetStringMap provides a mock function with given fields: key
func (_m *mockRawGetter) GetStringMap(key string) map[string]interface{} {
	ret := _m.Called(key)

	var r0 map[string]interface{}
	if rf, ok := ret.Get(0).(func(string) map[string]interface{}); ok {
		r0 = rf(key)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]interface{})
		}
	}

	return r0
}
