// Code generated by mockery v1.0.0
package externalmocks

import mock "github.com/stretchr/testify/mock"
import types "gitlab.com/swarmfund/go/doorman/types"

// Doorman is an autogenerated mock type for the Doorman type
type Doorman struct {
	mock.Mock
}

// MasterSigner provides a mock function with given fields: address
func (_m *Doorman) MasterSigner(address string) types.SignerConstraint {
	ret := _m.Called(address)

	var r0 types.SignerConstraint
	if rf, ok := ret.Get(0).(func(string) types.SignerConstraint); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.SignerConstraint)
		}
	}

	return r0
}

// SignerOf provides a mock function with given fields: address
func (_m *Doorman) SignerOf(address string) types.SignerConstraint {
	ret := _m.Called(address)

	var r0 types.SignerConstraint
	if rf, ok := ret.Get(0).(func(string) types.SignerConstraint); ok {
		r0 = rf(address)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(types.SignerConstraint)
		}
	}

	return r0
}
